on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Install Haxe
        run: haxe -version
      
      - name: Install Reflaxe
        run: haxelib git reflaxe https://github.com/RobertBorghese/reflaxe.git
      
      - name: Run Tests
        run: haxe "./test/unit_testing/TestAll.hxml"
          
