on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    name: Test on Ubuntu (GCC)
    steps:
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.0

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64

      - name: Install & Check Haxe
        run: haxe -version

      - name: Install Reflaxe
        run: haxelib git reflaxe https://github.com/SomeRanDev/reflaxe.git

      - name: Run Tests
        run: haxe Test.hxml

  build_windows:
    runs-on: windows-2019
    name: Test on Windows (VS)
    steps:
      - uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.0

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup VS
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
          vsversion: "2019"

      - name: Install & Check Haxe
        run: haxe -version

      - name: Install Reflaxe
        run: haxelib git reflaxe https://github.com/SomeRanDev/reflaxe.git

      - name: Run Tests
        run: haxe Test.hxml
